language: node_js
node_js:
  - '0.10'
script: npm run travis
notifications:
  email:
    recipients:
      - ypt-team@yahoo-inc.com
    on_success: change
    on_failure: always
env:
  global:
    - secure: 1r3HJvCAiLtqo4neotDQC8pPM0uB/45RUBmrjkELfGg02Eo2HYP0d8jBqDSR48e4O5/6Zw4lQPLLgDV7Ix3wNCo9yqIH1NDXnkBWcEShRzzJD1dJpCS+zCJXmuh9IqXOr+Sd93jNXADc6xVk8vUWaAOfaIK0vBiQmrq4GxLyYc4=
    - secure: qtUKktaUsfHgDK4ncpEVRTYV4T7pEZPOASB26EkCyyG8MgIfp827O9VmM3NtE6rPT4ymMuGvaRyCrt6cea5duhOnu0XyaoHR+IxRH+r67/qHKXzQ9dRMNbGD+UME6ozhMLgGAh1ZsWZ/QL9ei7WvtZID0IBbwxWZ/sYQZwa8Jho=
addons:
  sauce_connect: true
